server:
  port: ${PORT:9090}

spring:
  application:
    name: mock-chain-adapter

app:
  failure-rate: ${FAILURE_RATE:0.05}
  block-time-ms: ${BLOCK_TIME_MS:500}

logging:
  level:
    com.funkywallet: DEBUG
