apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: funky-wallet

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - signing-coordinator.yaml
  - evm-chain-adapter.yaml
  - solana-chain-adapter.yaml
  - wallet-api-service.yaml
  - funky-wallet-ui.yaml
