apiVersion: v1
kind: Secret
metadata:
  name: funky-wallet-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "funky-wallet.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-username: {{ .Values.secrets.postgresUsername | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  auth0-domain:      {{ .Values.secrets.auth0Domain | quote }}
  auth0-client-id:   {{ .Values.secrets.auth0ClientId | quote }}
  auth0-audience:    {{ .Values.secrets.auth0Audience | quote }}
